### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by eri451** [c3d2/ambiente#1]
```
yarn start v0.27.5
$ node main.js
ambiente/main.js:16
for (let i = 0; i < W; i++) {
     ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
error Command failed with exit code 1.
```

**Comment by eri451** [comment]
use node_8.x repository
